VERBOSE   = 0
SIMULATOR = vsim
MODULE    = mem_sp.sv
DEPENDS   =
TARGET    = test/test_$(MODULE)
SOURCES   = $(wildcard *.sv)
HEADERS   = $(wildcard *.svh)
TESTSUITE = $(wildcard test/*.sv)
INCLUDE   =
DIST      = ../../dist

include ../Makefile

